Output sequence.gif
# Output sequence.mp4

Set Shell "bash"
Set FontSize 20
Set Width 1200
Set Height 800
# Set CornerRadius 10
Set Padding 20
Set Theme "Catppuccin Mocha"

Type "zago new.md"

Sleep 500ms
Enter
Sleep 500ms
Type "# welcome to zago"
Enter
Enter
Sleep 500ms

Escape
Type "set canvas-mode on"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "BOX 10 Alice"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 3:30"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type `BOX "Bob 10`
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 5:6"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "VLINE 20"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 5:36"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "VLINE 20"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 8:7"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "LINE ARROW"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 7:10"
Sleep 500ms
Enter
Sleep 500ms
Type "Ping"
Sleep 500ms

Escape
Type "GOTO 11:7"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "LINE BACKARROW"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 10:10"
Sleep 500ms
Enter
Sleep 500ms
Type "Pong"
Sleep 500ms

Escape
Type "GOTO 13:6"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "LINE DOUBLE"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 15:6"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "LINE DOUBLE ARROW"
Sleep 500ms
Enter
Sleep 500ms


Escape
Type "GOTO 17:6"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "LINE ASCII"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "GOTO 19:6"
Sleep 500ms
Enter
Sleep 500ms

Escape
Type "LINE ASCII ARROW"
Sleep 500ms
Enter
Sleep 500ms

Sleep 2000ms